# **Combined JSON Cleaning**

In [37]:
import json
import glob
import os
import re

# Define the directory containing the JSON files
directory = "content_json"  # Update this path to your directory

# Define the pattern to match your JSON files
pattern = os.path.join(directory, "page_dval_*.json")


# Custom function to extract the numeric part (including negative) from the filename
def extract_number(filename):
    match = re.search(r"(-?\d+)", filename)  # Handle negative numbers
    if match:
        return int(match.group(1))
    return 0


# Get a sorted list of all files matching the pattern
file_list = sorted(glob.glob(pattern), key=extract_number)

# List to store all the data
combined_data = []

# Debug: Print the files being processed
print("Files to process in order:")
for file_name in file_list:
    print(f" - {file_name}")

# Read each JSON file and append its data to the combined_data list
for file_name in file_list:
    try:
        with open(file_name, "r", encoding="utf-8") as file:
            data = json.load(file)
            combined_data.extend(data)
            print(f"Loaded {len(data)} items from {file_name}")
    except Exception as e:
        print(f"Error processing {file_name}: {e}")

# Write the combined data to a new JSON file
output_file = "combined_file.json"
try:
    with open(output_file, "w", encoding="utf-8") as file:
        json.dump(combined_data, file, ensure_ascii=False, indent=4)
    print(f"Combined data written to {output_file}")
except Exception as e:
    print(f"Error writing to {output_file}: {e}")

Files to process in order:
 - content_json/page_dval_-199.json
 - content_json/page_dval_1.json
 - content_json/page_dval_201.json
 - content_json/page_dval_401.json
 - content_json/page_dval_601.json
 - content_json/page_dval_801.json
 - content_json/page_dval_1001.json
 - content_json/page_dval_1201.json
 - content_json/page_dval_1401.json
 - content_json/page_dval_1601.json
 - content_json/page_dval_1801.json
 - content_json/page_dval_2001.json
 - content_json/page_dval_2201.json
 - content_json/page_dval_2401.json
 - content_json/page_dval_2601.json
 - content_json/page_dval_2801.json
 - content_json/page_dval_3001.json
 - content_json/page_dval_3201.json
 - content_json/page_dval_3401.json
 - content_json/page_dval_3601.json
 - content_json/page_dval_3801.json
 - content_json/page_dval_4001.json
 - content_json/page_dval_4201.json
 - content_json/page_dval_4401.json
 - content_json/page_dval_4601.json
 - content_json/page_dval_4801.json
 - content_json/page_dval_5001.json
 - content_json/page_dval_5201.json
 - content_json/page_dval_5401.json
 - content_json/page_dval_5601.json
 - content_json/page_dval_5801.json
 - content_json/page_dval_6001.json
 - content_json/page_dval_6201.json
 - content_json/page_dval_6401.json
 - content_json/page_dval_6601.json
 - content_json/page_dval_6801.json
 - content_json/page_dval_7001.json
 - content_json/page_dval_7201.json
 - content_json/page_dval_7401.json
 - content_json/page_dval_7601.json
 - content_json/page_dval_7801.json
 - content_json/page_dval_8001.json
 - content_json/page_dval_8201.json
 - content_json/page_dval_8401.json
 - content_json/page_dval_8601.json
 - content_json/page_dval_8801.json
 - content_json/page_dval_9001.json
 - content_json/page_dval_9201.json
 - content_json/page_dval_9401.json
 - content_json/page_dval_9601.json
 - content_json/page_dval_9801.json
 - content_json/page_dval_10001.json
 - content_json/page_dval_10201.json
 - content_json/page_dval_10401.json
 - content_json/page_dval_10601.json
 - content_json/page_dval_10801.json
 - content_json/page_dval_11001.json
 - content_json/page_dval_11201.json
 - content_json/page_dval_11401.json
 - content_json/page_dval_11601.json
 - content_json/page_dval_11801.json
 - content_json/page_dval_12001.json
 - content_json/page_dval_12201.json
 - content_json/page_dval_12401.json
 - content_json/page_dval_12601.json
 - content_json/page_dval_12801.json
 - content_json/page_dval_13001.json
 - content_json/page_dval_13201.json
 - content_json/page_dval_13401.json
 - content_json/page_dval_13601.json
 - content_json/page_dval_13801.json
 - content_json/page_dval_14001.json
 - content_json/page_dval_14201.json
 - content_json/page_dval_14401.json
 - content_json/page_dval_14601.json
 - content_json/page_dval_14801.json
 - content_json/page_dval_15001.json
 - content_json/page_dval_15201.json
 - content_json/page_dval_15401.json
 - content_json/page_dval_15601.json
 - content_json/page_dval_15801.json
 - content_json/page_dval_16001.json
 - content_json/page_dval_16201.json
 - content_json/page_dval_16401.json
 - content_json/page_dval_16601.json
 - content_json/page_dval_16801.json
 - content_json/page_dval_17001.json
 - content_json/page_dval_17201.json
 - content_json/page_dval_17401.json
 - content_json/page_dval_17601.json
 - content_json/page_dval_17801.json
 - content_json/page_dval_18001.json
 - content_json/page_dval_18201.json
 - content_json/page_dval_18401.json
 - content_json/page_dval_18601.json
 - content_json/page_dval_18801.json
 - content_json/page_dval_19001.json
 - content_json/page_dval_19201.json
 - content_json/page_dval_19401.json
 - content_json/page_dval_19601.json
 - content_json/page_dval_19801.json
 - content_json/page_dval_20001.json
 - content_json/page_dval_20201.json
 - content_json/page_dval_20401.json
 - content_json/page_dval_20601.json
 - content_json/page_dval_20801.json
 - content_json/page_dval_21001.json
 - content_json/page_dval_21201.json
 - content_json/page_dval_21401.json
 - content_json/page_dval_21601.json
 - content_json/page_dval_21801.json
 - content_json/page_dval_22001.json
 - content_json/page_dval_22201.json
 - content_json/page_dval_22401.json
 - content_json/page_dval_22601.json
 - content_json/page_dval_22801.json
 - content_json/page_dval_23001.json
 - content_json/page_dval_23201.json
 - content_json/page_dval_23401.json
 - content_json/page_dval_23601.json
 - content_json/page_dval_23801.json
 - content_json/page_dval_24001.json
 - content_json/page_dval_24201.json
 - content_json/page_dval_24401.json
 - content_json/page_dval_24601.json
 - content_json/page_dval_24801.json
 - content_json/page_dval_25001.json
 - content_json/page_dval_25201.json
 - content_json/page_dval_25401.json
 - content_json/page_dval_25601.json
 - content_json/page_dval_25801.json
 - content_json/page_dval_26001.json
 - content_json/page_dval_26201.json
 - content_json/page_dval_26401.json
 - content_json/page_dval_26601.json
 - content_json/page_dval_26801.json
 - content_json/page_dval_27001.json
 - content_json/page_dval_27201.json
 - content_json/page_dval_27401.json
 - content_json/page_dval_27601.json
 - content_json/page_dval_27801.json
 - content_json/page_dval_28001.json
 - content_json/page_dval_28201.json
 - content_json/page_dval_28401.json
 - content_json/page_dval_28601.json
 - content_json/page_dval_28801.json
 - content_json/page_dval_29001.json
 - content_json/page_dval_29201.json
Loaded 933 items from content_json/page_dval_-199.json
Loaded 525 items from content_json/page_dval_1.json
Loaded 395 items from content_json/page_dval_201.json
Loaded 551 items from content_json/page_dval_401.json
Loaded 905 items from content_json/page_dval_601.json
Loaded 501 items from content_json/page_dval_801.json
Loaded 586 items from content_json/page_dval_1001.json
Loaded 0 items from content_json/page_dval_1201.json
Loaded 0 items from content_json/page_dval_1401.json
Loaded 749 items from content_json/page_dval_1601.json
Loaded 338 items from content_json/page_dval_1801.json
Loaded 279 items from content_json/page_dval_2001.json
Loaded 304 items from content_json/page_dval_2201.json
Loaded 308 items from content_json/page_dval_2401.json
Loaded 1155 items from content_json/page_dval_2601.json
Loaded 315 items from content_json/page_dval_2801.json
Loaded 744 items from content_json/page_dval_3001.json
Loaded 358 items from content_json/page_dval_3201.json
Loaded 938 items from content_json/page_dval_3401.json
Loaded 296 items from content_json/page_dval_3601.json
Loaded 478 items from content_json/page_dval_3801.json
Loaded 250 items from content_json/page_dval_4001.json
Loaded 318 items from content_json/page_dval_4201.json
Loaded 1236 items from content_json/page_dval_4401.json
Loaded 312 items from content_json/page_dval_4601.json
Loaded 522 items from content_json/page_dval_4801.json
Loaded 496 items from content_json/page_dval_5001.json
Loaded 1028 items from content_json/page_dval_5201.json
Loaded 383 items from content_json/page_dval_5401.json
Loaded 1261 items from content_json/page_dval_5601.json
Loaded 391 items from content_json/page_dval_5801.json
Loaded 1360 items from content_json/page_dval_6001.json
Loaded 532 items from content_json/page_dval_6201.json
Loaded 398 items from content_json/page_dval_6401.json
Loaded 403 items from content_json/page_dval_6601.json
Loaded 0 items from content_json/page_dval_6801.json
Loaded 1091 items from content_json/page_dval_7001.json
Loaded 673 items from content_json/page_dval_7201.json
Loaded 494 items from content_json/page_dval_7401.json
Loaded 774 items from content_json/page_dval_7601.json
Loaded 726 items from content_json/page_dval_7801.json
Loaded 432 items from content_json/page_dval_8001.json
Loaded 340 items from content_json/page_dval_8201.json
Loaded 410 items from content_json/page_dval_8401.json
Loaded 517 items from content_json/page_dval_8601.json
Loaded 812 items from content_json/page_dval_8801.json
Loaded 591 items from content_json/page_dval_9001.json
Loaded 449 items from content_json/page_dval_9201.json
Loaded 913 items from content_json/page_dval_9401.json
Loaded 536 items from content_json/page_dval_9601.json
Loaded 687 items from content_json/page_dval_9801.json
Loaded 536 items from content_json/page_dval_10001.json
Loaded 246 items from content_json/page_dval_10201.json
Loaded 1786 items from content_json/page_dval_10401.json
Loaded 329 items from content_json/page_dval_10601.json
Loaded 698 items from content_json/page_dval_10801.json
Loaded 354 items from content_json/page_dval_11001.json
Loaded 632 items from content_json/page_dval_11201.json
Loaded 410 items from content_json/page_dval_11401.json
Loaded 1221 items from content_json/page_dval_11601.json
Loaded 789 items from content_json/page_dval_11801.json
Loaded 620 items from content_json/page_dval_12001.json
Loaded 847 items from content_json/page_dval_12201.json
Loaded 501 items from content_json/page_dval_12401.json
Loaded 510 items from content_json/page_dval_12601.json
Loaded 337 items from content_json/page_dval_12801.json
Loaded 360 items from content_json/page_dval_13001.json
Loaded 807 items from content_json/page_dval_13201.json
Loaded 0 items from content_json/page_dval_13401.json
Loaded 291 items from content_json/page_dval_13601.json
Loaded 357 items from content_json/page_dval_13801.json
Loaded 738 items from content_json/page_dval_14001.json
Loaded 0 items from content_json/page_dval_14201.json
Loaded 487 items from content_json/page_dval_14401.json
Loaded 346 items from content_json/page_dval_14601.json
Loaded 398 items from content_json/page_dval_14801.json
Loaded 381 items from content_json/page_dval_15001.json
Loaded 827 items from content_json/page_dval_15201.json
Loaded 372 items from content_json/page_dval_15401.json
Loaded 347 items from content_json/page_dval_15601.json
Loaded 381 items from content_json/page_dval_15801.json
Loaded 356 items from content_json/page_dval_16001.json
Loaded 274 items from content_json/page_dval_16201.json
Loaded 397 items from content_json/page_dval_16401.json
Loaded 259 items from content_json/page_dval_16601.json
Loaded 249 items from content_json/page_dval_16801.json
Loaded 344 items from content_json/page_dval_17001.json
Loaded 242 items from content_json/page_dval_17201.json
Loaded 498 items from content_json/page_dval_17401.json
Loaded 300 items from content_json/page_dval_17601.json
Loaded 270 items from content_json/page_dval_17801.json
Loaded 256 items from content_json/page_dval_18001.json
Loaded 308 items from content_json/page_dval_18201.json
Loaded 275 items from content_json/page_dval_18401.json
Loaded 512 items from content_json/page_dval_18601.json
Loaded 267 items from content_json/page_dval_18801.json
Loaded 299 items from content_json/page_dval_19001.json
Loaded 397 items from content_json/page_dval_19201.json
Loaded 589 items from content_json/page_dval_19401.json
Loaded 537 items from content_json/page_dval_19601.json
Loaded 391 items from content_json/page_dval_19801.json
Loaded 388 items from content_json/page_dval_20001.json
Loaded 443 items from content_json/page_dval_20201.json
Loaded 519 items from content_json/page_dval_20401.json
Loaded 415 items from content_json/page_dval_20601.json
Loaded 272 items from content_json/page_dval_20801.json
Loaded 260 items from content_json/page_dval_21001.json
Loaded 292 items from content_json/page_dval_21201.json
Loaded 478 items from content_json/page_dval_21401.json
Loaded 243 items from content_json/page_dval_21601.json
Loaded 282 items from content_json/page_dval_21801.json
Loaded 449 items from content_json/page_dval_22001.json
Loaded 423 items from content_json/page_dval_22201.json
Loaded 361 items from content_json/page_dval_22401.json
Loaded 250 items from content_json/page_dval_22601.json
Loaded 246 items from content_json/page_dval_22801.json
Loaded 257 items from content_json/page_dval_23001.json
Loaded 252 items from content_json/page_dval_23201.json
Loaded 464 items from content_json/page_dval_23401.json
Loaded 250 items from content_json/page_dval_23601.json
Loaded 253 items from content_json/page_dval_23801.json
Loaded 379 items from content_json/page_dval_24001.json
Loaded 439 items from content_json/page_dval_24201.json
Loaded 347 items from content_json/page_dval_24401.json
Loaded 483 items from content_json/page_dval_24601.json
Loaded 316 items from content_json/page_dval_24801.json
Loaded 291 items from content_json/page_dval_25001.json
Loaded 334 items from content_json/page_dval_25201.json
Loaded 249 items from content_json/page_dval_25401.json
Loaded 264 items from content_json/page_dval_25601.json
Loaded 388 items from content_json/page_dval_25801.json
Loaded 262 items from content_json/page_dval_26001.json
Loaded 260 items from content_json/page_dval_26201.json
Loaded 254 items from content_json/page_dval_26401.json
Loaded 297 items from content_json/page_dval_26601.json
Loaded 229 items from content_json/page_dval_26801.json
Loaded 218 items from content_json/page_dval_27001.json
Loaded 335 items from content_json/page_dval_27201.json
Loaded 237 items from content_json/page_dval_27401.json
Loaded 221 items from content_json/page_dval_27601.json
Loaded 230 items from content_json/page_dval_27801.json
Loaded 224 items from content_json/page_dval_28001.json
Loaded 223 items from content_json/page_dval_28201.json
Loaded 274 items from content_json/page_dval_28401.json
Loaded 210 items from content_json/page_dval_28601.json
Loaded 206 items from content_json/page_dval_28801.json
Loaded 202 items from content_json/page_dval_29001.json
Loaded 181 items from content_json/page_dval_29201.json
Combined data written to combined_file.json

In [38]:
import pandas as pd

pd.set_option("display.max_colwidth", None)

combined_json_import = pd.read_json("combined_file.json")
combined_json_import

,level,details,action
0,1,"[مرسوم رئاسي رقم 94-465 ممضي في 25 ديسمبر 1994, وزارة الداخلية والجماعات المحلية والبيئة والإصلاح الإداري, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 4, يتضمن إحداث مجلس أعلى للبيئة والتنمية المستديمة ويحدد صلاحياته وتنظيمه وعمله.]",NaN
1,1,"[مرسوم تنفيذي رقم 94-462 ممضي في 21 ديسمبر 1994, المجلس الوطني الاقتصادي والاجتماعي, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 5, يتضمن الموافقة على اللائحة التي تحدد مبالغ التعويضات الممنوحة لأعضاء المجلس الوطني الاقتصادي والاجتماعي وتضبط كيفيات تطبيقها.]",NaN
2,1,"[مرسوم تنفيذي رقم 94-466 ممضي في 25 ديسمبر 1994, مصالح رئاسة الحكومة, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 7, يتعلق بتوظيف الدفعة الأولى من طلبة المدرسة الوطنية العليا للإدارة والتسيير.]",NaN
3,1,"[مرسوم تنفيذي رقم 94-467 ممضي في 25 ديسمبر 1994, وزارة الصناعة والطاقة, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 8, يضبط كيفيات تحديد الأسعار القاعدية للمحروقات وإجراءاته.]",NaN
4,1,"[مرسوم تنفيذي رقم 94-468 ممضي في 25 ديسمبر 1994, وزارة التكوين المهني, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 9, يتضمن حل مركز التكوين المهني والتمهين بمغنية ( II ) وتحويل أملاكه وحقوقه وإلتزاماته إلى وزارة المالية ( المديرية العامة للجمارك ).]",NaN
...,...,...,...
66266,1,"[قرار وزاري مشترك ممضي في 24 يوليو 2024, وزارة التعليم العالي والبحث العلمي, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 11, يتمم القرار الوزاري المشترك المؤرخ في 12 محرم عام 1441 الموافق 12 سبتمبر سنة 2019 الذي يحدد تصنيف المدرسة العليا وشروط الالتحاق بالمناصب العليا التابعة لها.]",NaN
66267,1,"[قرار وزاري مشترك ممضي في 04 غشت 2024, وزارة التعليم العالي والبحث العلمي, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 14, يحدد تعداد مناصب الشغل وتصنيفها ومدة العقد الخاص بالأعوان العاملين في نشاطات الحفظ أو الصيانة أو الخدمات بعنوان المؤسسات العمومية ذات الطابع العلمي والتكنولوجي تحت وصاية وزارة التعليم العالي والبحث العلمي.]",NaN
66268,1,"[قرار وزاري مشترك ممضي في 04 غشت 2024, وزارة الصناعة والإنتاج الصيدلاني, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 16, يحدد تنظيم الإدارة المركزية لوزارة الصناعة والإنتاج الصيدلاني في مكاتب.]",NaN
66269,1,"[قرار وزاري مشترك ممضي في 06 غشت 2024, وزارة النقل, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 23, يحدد تشكيلة اللجنة الاستشارية للحسابات الانتقالية والحسابات الجارية الانتقالية وتنظيمها وسيرها.]",NaN
66270,1,"[قرار ممضي في 28 ديسمبر 2023, وزارة الصيد البحري والمنتجات الصيدية, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 24, يعدل ويتمم القرار المؤرخ في 5 رجب عام 1442 الموافق 17 فبراير سنة 2021 والمتضمن إنشاء اللجان الإدارية المتساوية الأعضاء المختصة إزاء أسلاك موظفي الإدارة المركزية لوزارة الصيد البحري والمنتجات الصيدية., النصوص من 29401 إلى 29578 العدد 29578, ]",NaN

In [39]:
combined_json_import = combined_json_import[combined_json_import["level"] != 3]

# Optionally, reset the index if you need a clean DataFrame
combined_json_import.reset_index(drop=True, inplace=True)

## Clean the `details` column

---

In [40]:
combined_json_import["details"].apply(len).value_counts()

details
4    28379
3    15660
1      209
6      113
5       21
Name: count, dtype: int64

In [41]:
37991 + 489

38480

In [42]:
combined_json_import[combined_json_import.details.apply(len) == 6].details

1088                                                                                                                                                            [مرسوم تنفيذي رقم 95-285 ممضي في 18 سبتمبر 1995, وزارة المالية, الجريدة الرسمية عدد 55 مؤرخة في 27 سبتمبر 1995، الصفحة 21, يتضمن نقل إعتماد في ميزانية تسيير وزارة التعليم العالي والبحث العلمي., النصوص من 401 إلى 600 العدد 29578, ]
1495                                                                                                                                                                                  [مرسوم رئاسي رقم 95-382 ممضي في 28 نوفمبر 1995, وزارة المالية, الجريدة الرسمية عدد 73 مؤرخة في 29 نوفمبر 1995، الصفحة 8, يتضمن تحويل اعتماد إلى ميزانية تسيير وزارة العدل., النصوص من 601 إلى 800 العدد 29578, ]
2203                                                                                                                                                                                           [قرار ممضي في 10 فبراير 1996, وزارة الشؤون الخارجية, الجريدة الرسمية عدد 27 مؤرخة في 05 مايو 1996، الصفحة 29, يتضمن تفويض الإمضاء إلى مدير الزيارات والمؤتمرات., النصوص من 1001 إلى 1200 العدد 29578, ]
2504                                                                                                                                                                                                                      [قرار ممضي في 16 مارس 1996, وزارة المالية, الجريدة الرسمية عدد 45 مؤرخة في 24 يوليو 1996، الصفحة 50, تتضمن إعتماد وكلاء لدى الجمارك., النصوص من 1201 إلى 1400 العدد 29578, ]
3188                                                                                                                                                                                                  [مرسوم رئاسي رقم 97-211 ممضي في 10 يونيو 1997, رئاسة الجمهورية, الجريدة الرسمية عدد 41 مؤرخة في 15 يونيو 1997، الصفحة 3, يتضمن إنهاء مهام أعضاء الحكومة., النصوص من 2001 إلى 2200 العدد 29578, ]
                                                                                                                                                                                                     ...
43582                                                                                                                                                                                                   [قرار وزاري مشترك ممضي في 09 نوفمبر 2023, وزارة العدل, الجريدة الرسمية عدد 6 مؤرخة في 28 يناير 2024، الصفحة 15, يتضمن إحداث نشرة رسمية لوزارة العدل., النصوص من 28601 إلى 28800 العدد 29578, ]
43792                                                                                                                    [مرسوم رئاسي رقم 24-122 ممضي في 01 أبريل 2024, وزارة المالية, الجريدة الرسمية عدد 24 مؤرخة في 07 أبريل 2024، الصفحة 12, يتضمن تحويل اعتماد بعنوان ميزانية الدولة، يوضع تحت تصرف وزير الداخلية والجماعات المحلية والتهيئة العمرانية., النصوص من 28801 إلى 29000 العدد 29578, ]
43998    [قرار ممضي في 27 أبريل 2024, وزارة المالية, الجريدة الرسمية عدد 39 مؤرخة في 08 يونيو 2024، الصفحة 7, يعدل ويتمم القرار المؤرخ في 26 ذي القعدة عام 1434 الموافق 2 أكتوبر سنة 2013 الذي يحدد كيفيات تنظيم التكوين التحضيري لشغل بعض الرتب المنتمية للأسلاك الخاصة بالإدارة المكلفة بأملاك الدولة والحفظ العقاري ومسح الأراضي ومدته وكذا محتوى برامجه., النصوص من 29001 إلى 29200 العدد 29578, ]
44200                                                                                                                     [مرسوم رئاسي رقم 24-209 ممضي في 27 يونيو 2024, وزارة المالية, الجريدة الرسمية عدد 47 مؤرخة في 10 يوليو 2024، الصفحة 7, يتضمن تحويل اعتماد بعنوان ميزانية الدولة، يوضع تحت تصرف وزير الداخلية والجماعات المحلية والتهيئة العمرانية., النصوص من 29201 إلى 29400 العدد 29578, ]
44381                    [قرار ممضي في 28 ديسمبر 2023, وزارة الصيد البحري والمنتجات الصيدية, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 24, يعدل ويتمم القرار المؤرخ في 5 رجب عام 1442 الموافق 17 فبراير سنة 2021 والمتضمن إنشاء اللجان الإدارية المتساوية الأعضاء المختصة إزاء أسلاك موظفي الإدارة المركزية لوزارة الصيد البحري والمنتجات الصيدية., النصوص من 29401 إلى 29578 العدد 29578, ]
Name: details, Length: 113, dtype: object

In [43]:
print(combined_json_import[combined_json_import.details.apply(len) == 5].details)

831                                                                                                                                                                                      [قرار وزاري مشترك ممضي في 17 فبراير 1999, الجريدة الرسمية عدد 23 المؤرخة في 04 أبريل 1999، الصفحة 12, يتضمن إنشاء ملحقات للوكالة الوطنية لتطوير البحث الجامعي., النصوص من 201 إلى 400 العدد 29578, ]
1849                                                                                                                                                                                  [قرار ممضي في 15 يوليو 1998, الجريدة الرسمية عدد 67 المؤرخة في 09 سبتمبر 1998، الصفحة 11, يتعلق بجدول أسعار كراء العتاد المعمول به في حظائر مديريات الري للعتاد., النصوص من 801 إلى 1000 العدد 29578, ]
2911                                                                        [مرسوم تنفيذي رقم 02-112 ممضي في 03 أبريل 2002, الجريدة الرسمية عدد 22 المؤرخة في 03 أبريل 2002، الصفحة 10, يعدل المرسوم التنفيذي رقم 97-99 المؤرخ في 21 ذي القعدة عام 1417 الموافق 29 مارس سنة 1997 والمتضمن القانون الأساسي النموذجي لتعاونية الصناعة التقليدية والحرف., النصوص من 1801 إلى 2000 العدد 29578, ]
8317                                                                                                          [قرار ممضي في 05 سبتمبر 2011, الجريدة الرسمية عدد 19 المؤرخة في 01 أبريل 2012، الصفحة 33, يحدد القائمة الاسمية لأعضاء اللجنة الوزارية المشتركة المكلفة بمجانسة النصوص المتعلقة بالمهن والنشاطات المقننة الخاضعة للقيد في السجل التجاري., النصوص من 5201 إلى 5400 العدد 29578, ]
8600                                                                                                                            [قرار ممضي في 29 مايو 2005, الجريدة الرسمية عدد 77 المؤرخة في 30 نوفمبر 2005، الصفحة 12, يعدل القرار المؤرخ في 10 شعبان عام 1421 الموافق 6 نوفمبر سنة 2000 والمتضمن اعتماد "الشركة الجزائرية للتأمين وإعادة التأمين"., النصوص من 5401 إلى 5600 العدد 29578, ]
14457                                                                                                                                   [قرار ممضي في 07 أبريل 2010, الجريدة الرسمية عدد 33 المؤرخة في 19 مايو 2010، الصفحة 20, يحدد الاختبارات النظرية والعملية من أجل الحصول على تأهيل الطيران - طائرة - وعلى تأهيل الطيران بالأجهزة - هليكوبتر - ., النصوص من 9001 إلى 9200 العدد 29578, ]
17641                                                                                                                                                                                          [قرار ممضي في 19 مايو 2021, الجريدة الرسمية عدد 61 المؤرخة في 11 غشت 2021، الصفحة 18, يتضمن تعيين أعضاء مجلس إدارة الوكالة الوطنية لتطوير الاستثمار., النصوص من 10801 إلى 11000 العدد 29578, ]
18920                                                                                                                                                                                     [قرار ممضي في 20 سبتمبر 2011, الجريدة الرسمية عدد 47 المؤرخة في 29 غشت 2012، الصفحة 17, يحدد القائمة الإسمية لأعضاء المجلس التوجيهي للمتحف الوطني بشرشال., النصوص من 11401 إلى 11600 العدد 29578, ]
20360                                                                                                                                                                                                  [مرسوم تنفيذي رقم 24-224 ممضي في 02 يوليو 2024, الجريدة الرسمية عدد 48 المؤرخة في 14 يوليو 2024، الصفحة 12, يتضمن إنشاء ثانويات وإلغاء أخرى., النصوص من 12001 إلى 12200 العدد 29578, ]
21164                                                                                                                                          [مرسوم تنفيذي رقم 24-251 ممضي في 29 يوليو 2024, الجريدة الرسمية عدد 53 المؤرخة في 07 غشت 2024، الصفحة 13, يتضمن إلغاء تصنيف قطع أراض فلاحية موجهة لإنجاز صوامع لتخزين الحبوب على مستوى بعض الولايات., النصوص من 12401 إلى 12600 العدد 29578, ]
22109    [قرار وزاري مشترك ممضي في 14 يونيو 2023, الجريدة الرسمية عدد 55 المؤرخة في 27 غشت 2023، الصفحة 13, يعدل القرار الوزاري المشترك المؤرخ في 29 صفر عام 1430 الموافق 25 فبراير سنة 2009 الذي يحدد تعداد مناصب الشغل وتصنيفها ومدة العقد الخاص بالأعوان العاملين في نشاطات الحفظ أو الصيانة أو الخدمات بعنوان المديرية العامة للوظيفة العمومية., النصوص من 13001 إلى 13200 العدد 29578, ]
28712                                                                                                          [قرار وزاري مشترك ممضي في 20 سبتمبر 2016, الجريدة الرسمية عدد 60 المؤرخة في 13 أكتوبر 2016، الصفحة 31, يحدد كيفيات تحويل حق الانتفاع الدائم أو حق الامتياز إلى حق إيجار بالنسبة للأراضي الوقفية المخصصة للفلاحة المسترجعة من الدولة., النصوص من 17601 إلى 17800 العدد 29578, ]
29753                                     [قرار ممضي في 27 غشت 2018, الجريدة الرسمية عدد 61 المؤرخة في 14 أكتوبر 2018، الصفحة 25, يعدل القرار المؤرخ في 20 رجب عام 1435 الموافق 20 مايو سنة 2014 والمتضمن تقرير إعداد مخططات التهيئة السياحية لمناطق التوسع والمواقع السياحية لكل من شاطئ الشلف وخروبة ورميلة الوريعة وشاطئ ستيدية (ولاية مستغانم)., النصوص من 18401 إلى 18600 العدد 29578, ]
30559                                                                                                                                            [قرار ممضي في 15 نوفمبر 2018, الجريدة الرسمية عدد 30 المؤرخة في 08 مايو 2019، الصفحة 24, يتمم القرار المؤرخ في 15 جمادى الثانية عام 1436 الموافق 5 أبريل سنة 2015 الذي يحدد قائمة الفروع الفلاحية., النصوص من 19001 إلى 19200 العدد 29578, ]
30832                                                                                                                                                                                          [قرار وزاري مشترك ممضي في 04 أكتوبر 2016, الجريدة الرسمية عدد 39 المؤرخة في 02 يوليو 2017، الصفحة 14, يحدد المعايير الميكروبيولوجية للمواد الغذائية., النصوص من 19201 إلى 19400 العدد 29578, ]
31502                                                                                                      [قرار وزاري مشترك ممضي في 24 فبراير 2022, الجريدة الرسمية عدد 22 المؤرخة في 31 مارس 2022، الصفحة 23, يحدد كيفيات متابعة وتقييم حساب التخصيص الخاص رقم 131-302 الذي عنوانه "الصندوق الوطني للتحكم في الطاقة والطاقات المتجددة والمشتركة"., النصوص من 19601 إلى 19800 العدد 29578, ]
32151                                                                                                             [قرار ممضي في 06 ديسمبر 2018, الجريدة الرسمية عدد 5 المؤرخة في 23 يناير 2019، الصفحة 25, يعدل القرار المؤرّخ في 6 رجب عام 1437 الموافق 14 أبريل سنة 2016 والمتضمن تعيين أعضاء مجلس الإدارة لمشتلة المؤسسات المسماة "محضنة البيض"., النصوص من 20001 إلى 20200 العدد 29578, ]
33470                                                                                                          [قرار وزاري مشترك ممضي في 06 أبريل 2022, الجريدة الرسمية عدد 27 المؤرخة في 17 أبريل 2022، الصفحة 21, يحدد كيفيات متابعة وتقييم حساب التخصيص الخاص رقم 147-302 الذي عنوانه "تحسين وسائل تحصيل المصاريف القضائية والغرامات الجزائية "., النصوص من 20801 إلى 21000 العدد 29578, ]
33719                                                                                                               [قرار ممضي في 04 مارس 2019, الجريدة الرسمية عدد 39 المؤرخة في 16 يونيو 2019، الصفحة 22, يعدل القرار المؤرّخ في 21 شعبان عام 1437 الموافق 28 مايو سنة 2016 والمتضمن تعيين أعضاء مجلس إدارة الوكالة الوطنية لتحسين السكن وتطويره., النصوص من 21001 إلى 21200 العدد 29578, ]
34529                                 [قرار ممضي في 15 يونيو 2021, الجريدة الرسمية عدد 82 المؤرخة في 27 أكتوبر 2021، الصفحة 24, يعدل القرار المؤرخ في 10 صفر عام 1439 الموافق 31 أكتوبر سنة 2017 والمتضمن تعيين أعضاء مجلس إدارة الصندوق الوطني للعطل المدفوعة الأجر والبطالة الناجمة عن سوء الأحوال الجوية لقطاعات البناء والأشغال العمومية والري., النصوص من 21601 إلى 21800 العدد 29578, ]
38289                                                                                                   [قرار ممضي في 19 ديسمبر 2022, الجريدة الرسمية عدد 14 المؤرخة في 05 مارس 2023، الصفحة 23, يعدل القرار المؤرخ في 12 ذي الحجة عام 1441 الموافق 2 غشت سنة 2020 والمتضمن تعيين أعضاء مجلس إدارة المركز الوطني للتلقيح الاصطناعي وتحسين السلالات., النصوص من 24401 إلى 24600 العدد 29578, ]
Name: details, dtype: object

In [44]:
from copy import deepcopy

# Deepcopy the original data
combined_json = deepcopy(combined_json_import)


# Function to remove the last two elements or the last one based on length
def remove_last_two_elements(lst):
    if len(lst) == 6:
        return lst[:-2]  # Remove last two if length is 6
    elif len(lst) == 5:
        return lst[:-1]  # Remove last one if length is 5
    return lst  # Return unchanged if neither condition is met


# Apply the function to all rows in the 'details' column
combined_json["details"] = combined_json["details"].apply(remove_last_two_elements)

# Display the updated DataFrame
combined_json

,level,details,action
0,1,"[مرسوم رئاسي رقم 94-465 ممضي في 25 ديسمبر 1994, وزارة الداخلية والجماعات المحلية والبيئة والإصلاح الإداري, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 4, يتضمن إحداث مجلس أعلى للبيئة والتنمية المستديمة ويحدد صلاحياته وتنظيمه وعمله.]",NaN
1,1,"[مرسوم تنفيذي رقم 94-462 ممضي في 21 ديسمبر 1994, المجلس الوطني الاقتصادي والاجتماعي, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 5, يتضمن الموافقة على اللائحة التي تحدد مبالغ التعويضات الممنوحة لأعضاء المجلس الوطني الاقتصادي والاجتماعي وتضبط كيفيات تطبيقها.]",NaN
2,1,"[مرسوم تنفيذي رقم 94-466 ممضي في 25 ديسمبر 1994, مصالح رئاسة الحكومة, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 7, يتعلق بتوظيف الدفعة الأولى من طلبة المدرسة الوطنية العليا للإدارة والتسيير.]",NaN
3,1,"[مرسوم تنفيذي رقم 94-467 ممضي في 25 ديسمبر 1994, وزارة الصناعة والطاقة, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 8, يضبط كيفيات تحديد الأسعار القاعدية للمحروقات وإجراءاته.]",NaN
4,1,"[مرسوم تنفيذي رقم 94-468 ممضي في 25 ديسمبر 1994, وزارة التكوين المهني, الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 9, يتضمن حل مركز التكوين المهني والتمهين بمغنية ( II ) وتحويل أملاكه وحقوقه وإلتزاماته إلى وزارة المالية ( المديرية العامة للجمارك ).]",NaN
...,...,...,...
44377,1,"[قرار وزاري مشترك ممضي في 24 يوليو 2024, وزارة التعليم العالي والبحث العلمي, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 11, يتمم القرار الوزاري المشترك المؤرخ في 12 محرم عام 1441 الموافق 12 سبتمبر سنة 2019 الذي يحدد تصنيف المدرسة العليا وشروط الالتحاق بالمناصب العليا التابعة لها.]",NaN
44378,1,"[قرار وزاري مشترك ممضي في 04 غشت 2024, وزارة التعليم العالي والبحث العلمي, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 14, يحدد تعداد مناصب الشغل وتصنيفها ومدة العقد الخاص بالأعوان العاملين في نشاطات الحفظ أو الصيانة أو الخدمات بعنوان المؤسسات العمومية ذات الطابع العلمي والتكنولوجي تحت وصاية وزارة التعليم العالي والبحث العلمي.]",NaN
44379,1,"[قرار وزاري مشترك ممضي في 04 غشت 2024, وزارة الصناعة والإنتاج الصيدلاني, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 16, يحدد تنظيم الإدارة المركزية لوزارة الصناعة والإنتاج الصيدلاني في مكاتب.]",NaN
44380,1,"[قرار وزاري مشترك ممضي في 06 غشت 2024, وزارة النقل, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 23, يحدد تشكيلة اللجنة الاستشارية للحسابات الانتقالية والحسابات الجارية الانتقالية وتنظيمها وسيرها.]",NaN
44381,1,"[قرار ممضي في 28 ديسمبر 2023, وزارة الصيد البحري والمنتجات الصيدية, الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 24, يعدل ويتمم القرار المؤرخ في 5 رجب عام 1442 الموافق 17 فبراير سنة 2021 والمتضمن إنشاء اللجان الإدارية المتساوية الأعضاء المختصة إزاء أسلاك موظفي الإدارة المركزية لوزارة الصيد البحري والمنتجات الصيدية.]",NaN

In [45]:
combined_json["details"].apply(len).value_counts()

details
4    28513
3    15660
1      209
Name: count, dtype: int64

## Explode the `details` Column

---

In [46]:
def transform_list(row):
    # Handle different list lengths
    if len(row) == 4:
        return {"title": row[0], "author": row[1], "gazette": row[2], "summary": row[3]}
    elif len(row) == 3:
        return {"title": row[0], "author": None, "gazette": row[1], "summary": row[2]}
    elif len(row) == 1:
        return {"title": None, "author": None, "gazette": row[0], "summary": None}


# Apply the transformation function to the 'details' column
combined_json_details = combined_json["details"].apply(transform_list).apply(pd.Series)

# Concatenate with the original DataFrame if needed
combined_json_transformed = pd.concat(
    [combined_json.drop(columns=["details"]), combined_json_details], axis=1
)

combined_json_transformed

,level,action,title,author,gazette,summary
0,1,NaN,مرسوم رئاسي رقم 94-465 ممضي في 25 ديسمبر 1994,وزارة الداخلية والجماعات المحلية والبيئة والإصلاح الإداري,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 4,يتضمن إحداث مجلس أعلى للبيئة والتنمية المستديمة ويحدد صلاحياته وتنظيمه وعمله.
1,1,NaN,مرسوم تنفيذي رقم 94-462 ممضي في 21 ديسمبر 1994,المجلس الوطني الاقتصادي والاجتماعي,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 5,يتضمن الموافقة على اللائحة التي تحدد مبالغ التعويضات الممنوحة لأعضاء المجلس الوطني الاقتصادي والاجتماعي وتضبط كيفيات تطبيقها.
2,1,NaN,مرسوم تنفيذي رقم 94-466 ممضي في 25 ديسمبر 1994,مصالح رئاسة الحكومة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 7,يتعلق بتوظيف الدفعة الأولى من طلبة المدرسة الوطنية العليا للإدارة والتسيير.
3,1,NaN,مرسوم تنفيذي رقم 94-467 ممضي في 25 ديسمبر 1994,وزارة الصناعة والطاقة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 8,يضبط كيفيات تحديد الأسعار القاعدية للمحروقات وإجراءاته.
4,1,NaN,مرسوم تنفيذي رقم 94-468 ممضي في 25 ديسمبر 1994,وزارة التكوين المهني,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 9,يتضمن حل مركز التكوين المهني والتمهين بمغنية ( II ) وتحويل أملاكه وحقوقه وإلتزاماته إلى وزارة المالية ( المديرية العامة للجمارك ).
...,...,...,...,...,...,...
44377,1,NaN,قرار وزاري مشترك ممضي في 24 يوليو 2024,وزارة التعليم العالي والبحث العلمي,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 11,يتمم القرار الوزاري المشترك المؤرخ في 12 محرم عام 1441 الموافق 12 سبتمبر سنة 2019 الذي يحدد تصنيف المدرسة العليا وشروط الالتحاق بالمناصب العليا التابعة لها.
44378,1,NaN,قرار وزاري مشترك ممضي في 04 غشت 2024,وزارة التعليم العالي والبحث العلمي,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 14,يحدد تعداد مناصب الشغل وتصنيفها ومدة العقد الخاص بالأعوان العاملين في نشاطات الحفظ أو الصيانة أو الخدمات بعنوان المؤسسات العمومية ذات الطابع العلمي والتكنولوجي تحت وصاية وزارة التعليم العالي والبحث العلمي.
44379,1,NaN,قرار وزاري مشترك ممضي في 04 غشت 2024,وزارة الصناعة والإنتاج الصيدلاني,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 16,يحدد تنظيم الإدارة المركزية لوزارة الصناعة والإنتاج الصيدلاني في مكاتب.
44380,1,NaN,قرار وزاري مشترك ممضي في 06 غشت 2024,وزارة النقل,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 23,يحدد تشكيلة اللجنة الاستشارية للحسابات الانتقالية والحسابات الجارية الانتقالية وتنظيمها وسيرها.
44381,1,NaN,قرار ممضي في 28 ديسمبر 2023,وزارة الصيد البحري والمنتجات الصيدية,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 24,يعدل ويتمم القرار المؤرخ في 5 رجب عام 1442 الموافق 17 فبراير سنة 2021 والمتضمن إنشاء اللجان الإدارية المتساوية الأعضاء المختصة إزاء أسلاك موظفي الإدارة المركزية لوزارة الصيد البحري والمنتجات الصيدية.

## Clean Up After the Explosion

---

### `gazette` Column

In [47]:
combined_json_transformed_cleaned = deepcopy(combined_json_transformed)


def check_gazette_value(value):
    if "الجريدة الرسمية" not in value:
        return True
    return False


# Apply the function to the 'gazette' column
combined_json_transformed_cleaned[
    combined_json_transformed_cleaned["gazette"].apply(check_gazette_value)
].head()

,level,action,title,author,gazette,summary
831,2,نص تطبيقي,قرار وزاري مشترك ممضي في 17 فبراير 1999,الجريدة الرسمية عدد 23 المؤرخة في 04 أبريل 1999، الصفحة 12,يتضمن إنشاء ملحقات للوكالة الوطنية لتطوير البحث الجامعي.,النصوص من 201 إلى 400 العدد 29578
1849,2,نص تطبيقي,قرار ممضي في 15 يوليو 1998,الجريدة الرسمية عدد 67 المؤرخة في 09 سبتمبر 1998، الصفحة 11,يتعلق بجدول أسعار كراء العتاد المعمول به في حظائر مديريات الري للعتاد.,النصوص من 801 إلى 1000 العدد 29578
2911,2,معدل بـ,مرسوم تنفيذي رقم 02-112 ممضي في 03 أبريل 2002,الجريدة الرسمية عدد 22 المؤرخة في 03 أبريل 2002، الصفحة 10,يعدل المرسوم التنفيذي رقم 97-99 المؤرخ في 21 ذي القعدة عام 1417 الموافق 29 مارس سنة 1997 والمتضمن القانون الأساسي النموذجي لتعاونية الصناعة التقليدية والحرف.,النصوص من 1801 إلى 2000 العدد 29578
8317,2,نص تطبيقي,قرار ممضي في 05 سبتمبر 2011,الجريدة الرسمية عدد 19 المؤرخة في 01 أبريل 2012، الصفحة 33,يحدد القائمة الاسمية لأعضاء اللجنة الوزارية المشتركة المكلفة بمجانسة النصوص المتعلقة بالمهن والنشاطات المقننة الخاضعة للقيد في السجل التجاري.,النصوص من 5201 إلى 5400 العدد 29578
8600,2,معدل بـ,قرار ممضي في 29 مايو 2005,الجريدة الرسمية عدد 77 المؤرخة في 30 نوفمبر 2005، الصفحة 12,"يعدل القرار المؤرخ في 10 شعبان عام 1421 الموافق 6 نوفمبر سنة 2000 والمتضمن اعتماد ""الشركة الجزائرية للتأمين وإعادة التأمين"".",النصوص من 5401 إلى 5600 العدد 29578

In [48]:
combined_json_transformed_cleaned.loc[
    combined_json_transformed_cleaned["gazette"].apply(check_gazette_value), "summary"
] = None
combined_json_transformed_cleaned[
    combined_json_transformed_cleaned["gazette"].apply(check_gazette_value)
].head()

,level,action,title,author,gazette,summary
831,2,نص تطبيقي,قرار وزاري مشترك ممضي في 17 فبراير 1999,الجريدة الرسمية عدد 23 المؤرخة في 04 أبريل 1999، الصفحة 12,يتضمن إنشاء ملحقات للوكالة الوطنية لتطوير البحث الجامعي.,None
1849,2,نص تطبيقي,قرار ممضي في 15 يوليو 1998,الجريدة الرسمية عدد 67 المؤرخة في 09 سبتمبر 1998، الصفحة 11,يتعلق بجدول أسعار كراء العتاد المعمول به في حظائر مديريات الري للعتاد.,None
2911,2,معدل بـ,مرسوم تنفيذي رقم 02-112 ممضي في 03 أبريل 2002,الجريدة الرسمية عدد 22 المؤرخة في 03 أبريل 2002، الصفحة 10,يعدل المرسوم التنفيذي رقم 97-99 المؤرخ في 21 ذي القعدة عام 1417 الموافق 29 مارس سنة 1997 والمتضمن القانون الأساسي النموذجي لتعاونية الصناعة التقليدية والحرف.,None
8317,2,نص تطبيقي,قرار ممضي في 05 سبتمبر 2011,الجريدة الرسمية عدد 19 المؤرخة في 01 أبريل 2012، الصفحة 33,يحدد القائمة الاسمية لأعضاء اللجنة الوزارية المشتركة المكلفة بمجانسة النصوص المتعلقة بالمهن والنشاطات المقننة الخاضعة للقيد في السجل التجاري.,None
8600,2,معدل بـ,قرار ممضي في 29 مايو 2005,الجريدة الرسمية عدد 77 المؤرخة في 30 نوفمبر 2005، الصفحة 12,"يعدل القرار المؤرخ في 10 شعبان عام 1421 الموافق 6 نوفمبر سنة 2000 والمتضمن اعتماد ""الشركة الجزائرية للتأمين وإعادة التأمين"".",None

In [49]:
condition = combined_json_transformed_cleaned["gazette"].apply(check_gazette_value)

combined_json_transformed_cleaned.loc[condition, "temp"] = (
    combined_json_transformed_cleaned.loc[condition, "author"]
)

combined_json_transformed_cleaned.loc[condition, "author"] = None
combined_json_transformed_cleaned.loc[condition, "summary"] = (
    combined_json_transformed_cleaned.loc[condition, "gazette"]
)
combined_json_transformed_cleaned.loc[condition, "gazette"] = (
    combined_json_transformed_cleaned.loc[condition, "temp"]
)

combined_json_transformed_cleaned = combined_json_transformed_cleaned.drop(
    columns=["temp"]
)

combined_json_transformed_cleaned

,level,action,title,author,gazette,summary
0,1,NaN,مرسوم رئاسي رقم 94-465 ممضي في 25 ديسمبر 1994,وزارة الداخلية والجماعات المحلية والبيئة والإصلاح الإداري,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 4,يتضمن إحداث مجلس أعلى للبيئة والتنمية المستديمة ويحدد صلاحياته وتنظيمه وعمله.
1,1,NaN,مرسوم تنفيذي رقم 94-462 ممضي في 21 ديسمبر 1994,المجلس الوطني الاقتصادي والاجتماعي,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 5,يتضمن الموافقة على اللائحة التي تحدد مبالغ التعويضات الممنوحة لأعضاء المجلس الوطني الاقتصادي والاجتماعي وتضبط كيفيات تطبيقها.
2,1,NaN,مرسوم تنفيذي رقم 94-466 ممضي في 25 ديسمبر 1994,مصالح رئاسة الحكومة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 7,يتعلق بتوظيف الدفعة الأولى من طلبة المدرسة الوطنية العليا للإدارة والتسيير.
3,1,NaN,مرسوم تنفيذي رقم 94-467 ممضي في 25 ديسمبر 1994,وزارة الصناعة والطاقة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 8,يضبط كيفيات تحديد الأسعار القاعدية للمحروقات وإجراءاته.
4,1,NaN,مرسوم تنفيذي رقم 94-468 ممضي في 25 ديسمبر 1994,وزارة التكوين المهني,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 9,يتضمن حل مركز التكوين المهني والتمهين بمغنية ( II ) وتحويل أملاكه وحقوقه وإلتزاماته إلى وزارة المالية ( المديرية العامة للجمارك ).
...,...,...,...,...,...,...
44377,1,NaN,قرار وزاري مشترك ممضي في 24 يوليو 2024,وزارة التعليم العالي والبحث العلمي,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 11,يتمم القرار الوزاري المشترك المؤرخ في 12 محرم عام 1441 الموافق 12 سبتمبر سنة 2019 الذي يحدد تصنيف المدرسة العليا وشروط الالتحاق بالمناصب العليا التابعة لها.
44378,1,NaN,قرار وزاري مشترك ممضي في 04 غشت 2024,وزارة التعليم العالي والبحث العلمي,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 14,يحدد تعداد مناصب الشغل وتصنيفها ومدة العقد الخاص بالأعوان العاملين في نشاطات الحفظ أو الصيانة أو الخدمات بعنوان المؤسسات العمومية ذات الطابع العلمي والتكنولوجي تحت وصاية وزارة التعليم العالي والبحث العلمي.
44379,1,NaN,قرار وزاري مشترك ممضي في 04 غشت 2024,وزارة الصناعة والإنتاج الصيدلاني,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 16,يحدد تنظيم الإدارة المركزية لوزارة الصناعة والإنتاج الصيدلاني في مكاتب.
44380,1,NaN,قرار وزاري مشترك ممضي في 06 غشت 2024,وزارة النقل,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 23,يحدد تشكيلة اللجنة الاستشارية للحسابات الانتقالية والحسابات الجارية الانتقالية وتنظيمها وسيرها.
44381,1,NaN,قرار ممضي في 28 ديسمبر 2023,وزارة الصيد البحري والمنتجات الصيدية,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 24,يعدل ويتمم القرار المؤرخ في 5 رجب عام 1442 الموافق 17 فبراير سنة 2021 والمتضمن إنشاء اللجان الإدارية المتساوية الأعضاء المختصة إزاء أسلاك موظفي الإدارة المركزية لوزارة الصيد البحري والمنتجات الصيدية.

In [50]:
condition = combined_json_transformed_cleaned["gazette"].apply(check_gazette_value)

# Swap data between 'author', 'gazette', and 'summary' columns
# Step 1: Create a temporary column to hold the data during the swap
combined_json_transformed_cleaned.loc[condition, "temp"] = (
    combined_json_transformed_cleaned.loc[condition, "author"]
)

# Step 2: Perform the swap
combined_json_transformed_cleaned.loc[condition, "author"] = (
    combined_json_transformed_cleaned.loc[condition, "gazette"]
)
combined_json_transformed_cleaned.loc[condition, "gazette"] = (
    combined_json_transformed_cleaned.loc[condition, "summary"]
)
combined_json_transformed_cleaned.loc[condition, "summary"] = (
    combined_json_transformed_cleaned.loc[condition, "temp"]
)

# Step 3: Drop the temporary column
combined_json_transformed_cleaned = combined_json_transformed_cleaned.drop(
    columns=["temp"]
)

combined_json_transformed_cleaned

,level,action,title,author,gazette,summary
0,1,NaN,مرسوم رئاسي رقم 94-465 ممضي في 25 ديسمبر 1994,وزارة الداخلية والجماعات المحلية والبيئة والإصلاح الإداري,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 4,يتضمن إحداث مجلس أعلى للبيئة والتنمية المستديمة ويحدد صلاحياته وتنظيمه وعمله.
1,1,NaN,مرسوم تنفيذي رقم 94-462 ممضي في 21 ديسمبر 1994,المجلس الوطني الاقتصادي والاجتماعي,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 5,يتضمن الموافقة على اللائحة التي تحدد مبالغ التعويضات الممنوحة لأعضاء المجلس الوطني الاقتصادي والاجتماعي وتضبط كيفيات تطبيقها.
2,1,NaN,مرسوم تنفيذي رقم 94-466 ممضي في 25 ديسمبر 1994,مصالح رئاسة الحكومة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 7,يتعلق بتوظيف الدفعة الأولى من طلبة المدرسة الوطنية العليا للإدارة والتسيير.
3,1,NaN,مرسوم تنفيذي رقم 94-467 ممضي في 25 ديسمبر 1994,وزارة الصناعة والطاقة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 8,يضبط كيفيات تحديد الأسعار القاعدية للمحروقات وإجراءاته.
4,1,NaN,مرسوم تنفيذي رقم 94-468 ممضي في 25 ديسمبر 1994,وزارة التكوين المهني,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 9,يتضمن حل مركز التكوين المهني والتمهين بمغنية ( II ) وتحويل أملاكه وحقوقه وإلتزاماته إلى وزارة المالية ( المديرية العامة للجمارك ).
...,...,...,...,...,...,...
44377,1,NaN,قرار وزاري مشترك ممضي في 24 يوليو 2024,وزارة التعليم العالي والبحث العلمي,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 11,يتمم القرار الوزاري المشترك المؤرخ في 12 محرم عام 1441 الموافق 12 سبتمبر سنة 2019 الذي يحدد تصنيف المدرسة العليا وشروط الالتحاق بالمناصب العليا التابعة لها.
44378,1,NaN,قرار وزاري مشترك ممضي في 04 غشت 2024,وزارة التعليم العالي والبحث العلمي,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 14,يحدد تعداد مناصب الشغل وتصنيفها ومدة العقد الخاص بالأعوان العاملين في نشاطات الحفظ أو الصيانة أو الخدمات بعنوان المؤسسات العمومية ذات الطابع العلمي والتكنولوجي تحت وصاية وزارة التعليم العالي والبحث العلمي.
44379,1,NaN,قرار وزاري مشترك ممضي في 04 غشت 2024,وزارة الصناعة والإنتاج الصيدلاني,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 16,يحدد تنظيم الإدارة المركزية لوزارة الصناعة والإنتاج الصيدلاني في مكاتب.
44380,1,NaN,قرار وزاري مشترك ممضي في 06 غشت 2024,وزارة النقل,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 23,يحدد تشكيلة اللجنة الاستشارية للحسابات الانتقالية والحسابات الجارية الانتقالية وتنظيمها وسيرها.
44381,1,NaN,قرار ممضي في 28 ديسمبر 2023,وزارة الصيد البحري والمنتجات الصيدية,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 24,يعدل ويتمم القرار المؤرخ في 5 رجب عام 1442 الموافق 17 فبراير سنة 2021 والمتضمن إنشاء اللجان الإدارية المتساوية الأعضاء المختصة إزاء أسلاك موظفي الإدارة المركزية لوزارة الصيد البحري والمنتجات الصيدية.

### `title` Column

In [51]:
def check_title_value(value):
    if not value:
        return False
    if "ممضي" not in value:
        return True
    return False


combined_json_transformed_cleaned[
    combined_json_transformed_cleaned["title"].apply(check_title_value)
]

Empty DataFrame
Columns: [level, action, title, author, gazette, summary]
Index: []

### `author` Column

In [52]:
combined_json_transformed.author.isna().sum()

15869

## Extract The `year` and `number` from the `magazine` Column

---

In [53]:
import re

combined_json_final = deepcopy(combined_json_transformed_cleaned)


def extract_year_number(string):

    # Regex to extract number and year
    match = re.search(r"عدد (\d+).* (\d{4})", string)

    if match:
        number = match.group(1)
        year = match.group(2)
        return pd.Series([year, number])
    return pd.Series([None, None])


combined_json_final[["year", "number"]] = combined_json_final["gazette"].apply(
    extract_year_number
)
combined_json_final

,level,action,title,author,gazette,summary,year,number
0,1,NaN,مرسوم رئاسي رقم 94-465 ممضي في 25 ديسمبر 1994,وزارة الداخلية والجماعات المحلية والبيئة والإصلاح الإداري,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 4,يتضمن إحداث مجلس أعلى للبيئة والتنمية المستديمة ويحدد صلاحياته وتنظيمه وعمله.,1995,1
1,1,NaN,مرسوم تنفيذي رقم 94-462 ممضي في 21 ديسمبر 1994,المجلس الوطني الاقتصادي والاجتماعي,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 5,يتضمن الموافقة على اللائحة التي تحدد مبالغ التعويضات الممنوحة لأعضاء المجلس الوطني الاقتصادي والاجتماعي وتضبط كيفيات تطبيقها.,1995,1
2,1,NaN,مرسوم تنفيذي رقم 94-466 ممضي في 25 ديسمبر 1994,مصالح رئاسة الحكومة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 7,يتعلق بتوظيف الدفعة الأولى من طلبة المدرسة الوطنية العليا للإدارة والتسيير.,1995,1
3,1,NaN,مرسوم تنفيذي رقم 94-467 ممضي في 25 ديسمبر 1994,وزارة الصناعة والطاقة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 8,يضبط كيفيات تحديد الأسعار القاعدية للمحروقات وإجراءاته.,1995,1
4,1,NaN,مرسوم تنفيذي رقم 94-468 ممضي في 25 ديسمبر 1994,وزارة التكوين المهني,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 9,يتضمن حل مركز التكوين المهني والتمهين بمغنية ( II ) وتحويل أملاكه وحقوقه وإلتزاماته إلى وزارة المالية ( المديرية العامة للجمارك ).,1995,1
...,...,...,...,...,...,...,...,...
44377,1,NaN,قرار وزاري مشترك ممضي في 24 يوليو 2024,وزارة التعليم العالي والبحث العلمي,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 11,يتمم القرار الوزاري المشترك المؤرخ في 12 محرم عام 1441 الموافق 12 سبتمبر سنة 2019 الذي يحدد تصنيف المدرسة العليا وشروط الالتحاق بالمناصب العليا التابعة لها.,2024,60
44378,1,NaN,قرار وزاري مشترك ممضي في 04 غشت 2024,وزارة التعليم العالي والبحث العلمي,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 14,يحدد تعداد مناصب الشغل وتصنيفها ومدة العقد الخاص بالأعوان العاملين في نشاطات الحفظ أو الصيانة أو الخدمات بعنوان المؤسسات العمومية ذات الطابع العلمي والتكنولوجي تحت وصاية وزارة التعليم العالي والبحث العلمي.,2024,60
44379,1,NaN,قرار وزاري مشترك ممضي في 04 غشت 2024,وزارة الصناعة والإنتاج الصيدلاني,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 16,يحدد تنظيم الإدارة المركزية لوزارة الصناعة والإنتاج الصيدلاني في مكاتب.,2024,60
44380,1,NaN,قرار وزاري مشترك ممضي في 06 غشت 2024,وزارة النقل,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 23,يحدد تشكيلة اللجنة الاستشارية للحسابات الانتقالية والحسابات الجارية الانتقالية وتنظيمها وسيرها.,2024,60
44381,1,NaN,قرار ممضي في 28 ديسمبر 2023,وزارة الصيد البحري والمنتجات الصيدية,الجريدة الرسمية عدد 60 مؤرخة في 29 غشت 2024، الصفحة 24,يعدل ويتمم القرار المؤرخ في 5 رجب عام 1442 الموافق 17 فبراير سنة 2021 والمتضمن إنشاء اللجان الإدارية المتساوية الأعضاء المختصة إزاء أسلاك موظفي الإدارة المركزية لوزارة الصيد البحري والمنتجات الصيدية.,2024,60

In [54]:
combined_json_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44382 entries, 0 to 44381
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   level    44382 non-null  int64
 1   action   15804 non-null  object
 2   title    44173 non-null  object
 3   author   28492 non-null  object
 4   gazette  44382 non-null  object
 5   summary  44173 non-null  object
 6   year     44382 non-null  object
 7   number   44382 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.7+ MB

## Linking Parents to Children

---

In [55]:
combined_json_final.action.value_counts()

action
معدل بـ          6936
نص تطبيقي        5072
ملغى بـ          3239
استدراك في        464
موافق عليه بـ      93
Name: count, dtype: int64

In [56]:
combined_json_final.level.value_counts()

level
1    28578
2    15804
Name: count, dtype: int64

In [57]:
import numpy as np
from copy import deepcopy

# Make a deep copy of the original DataFrame
combined_json_flattened = deepcopy(combined_json_final)

# Initialize the children column as an empty list for every row
combined_json_flattened["modified_by"] =None
combined_json_flattened["cancelled_by"] =None
combined_json_flattened["approved_by"] =None
combined_json_flattened["rectified_in"] = None
combined_json_flattened["implemented_by"] =None
first_parent = None

# List to store indices of rows to drop after nesting
to_drop = []

In [58]:
# Nest level 2 inside level 1
for i in range(0, len(combined_json_flattened)):
    if combined_json_flattened.loc[i, "level"] == 1:
        # When encountering a level 1, mark it as the first parent
        first_parent = i
        combined_json_flattened.at[first_parent, "modified_by"] = []
        combined_json_flattened.at[first_parent, "approved_by"] = []
        combined_json_flattened.at[first_parent, "cancelled_by"] = []
        combined_json_flattened.at[first_parent, "rectified_in"] = []
        combined_json_flattened.at[first_parent, "implemented_by"] = []

    elif combined_json_flattened.loc[i, "level"] == 2:
        # Add level 2 entries (which already contain their children) as children of level 1
        child_row = combined_json_flattened.loc[i].to_dict()
        # child_row.pop("level", None)
        # child_row.pop("action", None)
        # child_row.pop("modified_by", None)
        # child_row.pop("approved_by", None)
        # child_row.pop("cancelled_by", None)
        # child_row.pop("rectified_in", None)
        # child_row.pop("implemented_by", None)

        if combined_json_flattened.loc[i, "action"] == "معدل بـ":
            combined_json_flattened.at[first_parent, "modified_by"].append(child_row)
            if i < 20:
                print(f"Added {i} to {first_parent} at modified")
        elif combined_json_flattened.loc[i, "action"] == "نص تطبيقي":
            combined_json_flattened.at[first_parent, "implemented_by"].append(child_row)
            if i < 20:
                print(f"Added {i} to {first_parent} at implemented_by")
        elif combined_json_flattened.loc[i, "action"] == "ملغى بـ":
            combined_json_flattened.at[first_parent, "cancelled_by"].append(child_row)
            if i < 20:
                print(f"Added {i} to {first_parent} at cancelled_by")
        elif combined_json_flattened.loc[i, "action"] == "استدراك في":
            combined_json_flattened.at[first_parent, "rectified_in"].append(child_row)
            if i < 20:
                print(f"Added {i} to {first_parent} at rectified_in")
        else:
            combined_json_flattened.at[first_parent, "approved_by"].append(child_row)
            if i < 20:
                print(f"Added {i} to {first_parent} at approved_by")

        to_drop.append(i)

# Drop level 2 and 3 rows (children) from the original DataFrame after nesting
combined_json_flattened.drop(index=to_drop, inplace=True)

# Reset index to maintain sequential order after dropping rows
combined_json_flattened.reset_index(drop=True, inplace=True)

combined_json_flattened.drop(columns=["level", "action"], inplace=True)

# Display the first few rows to verify
combined_json_flattened.head(10)

Added 6 to 5 at cancelled_by
Added 7 to 5 at modified
Added 9 to 8 at cancelled_by
Added 17 to 16 at cancelled_by

,title,author,gazette,summary,year,number,modified_by,cancelled_by,approved_by,rectified_in,implemented_by
0,مرسوم رئاسي رقم 94-465 ممضي في 25 ديسمبر 1994,وزارة الداخلية والجماعات المحلية والبيئة والإصلاح الإداري,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 4,يتضمن إحداث مجلس أعلى للبيئة والتنمية المستديمة ويحدد صلاحياته وتنظيمه وعمله.,1995,1,[],[],[],[],[]
1,مرسوم تنفيذي رقم 94-462 ممضي في 21 ديسمبر 1994,المجلس الوطني الاقتصادي والاجتماعي,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 5,يتضمن الموافقة على اللائحة التي تحدد مبالغ التعويضات الممنوحة لأعضاء المجلس الوطني الاقتصادي والاجتماعي وتضبط كيفيات تطبيقها.,1995,1,[],[],[],[],[]
2,مرسوم تنفيذي رقم 94-466 ممضي في 25 ديسمبر 1994,مصالح رئاسة الحكومة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 7,يتعلق بتوظيف الدفعة الأولى من طلبة المدرسة الوطنية العليا للإدارة والتسيير.,1995,1,[],[],[],[],[]
3,مرسوم تنفيذي رقم 94-467 ممضي في 25 ديسمبر 1994,وزارة الصناعة والطاقة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 8,يضبط كيفيات تحديد الأسعار القاعدية للمحروقات وإجراءاته.,1995,1,[],[],[],[],[]
4,مرسوم تنفيذي رقم 94-468 ممضي في 25 ديسمبر 1994,وزارة التكوين المهني,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 9,يتضمن حل مركز التكوين المهني والتمهين بمغنية ( II ) وتحويل أملاكه وحقوقه وإلتزاماته إلى وزارة المالية ( المديرية العامة للجمارك ).,1995,1,[],[],[],[],[]
5,مرسوم تنفيذي رقم 94-469 ممضي في 25 ديسمبر 1994,وزارة التكوين المهني,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 11,يحدد قائمة المناصب العليا في المصالح غير المركزية التابعة لوزارة التكوين المهني وشروط الالتحاق بها وتصنيفها.,1995,1,"[{'level': 2, 'action': 'معدل بـ', 'title': 'مرسوم تنفيذي رقم 97-331 ممضي في 10 سبتمبر 1997', 'author': None, 'gazette': 'الجريدة الرسمية عدد 60 المؤرخة في 10 سبتمبر 1997، الصفحة 12', 'summary': 'يعدل ويتمم المرسوم التنفيذي رقم 94-469 المؤرخ في 21 رجب عام 1415 الموافق 25 ديسمبر 1994 الذي يحدد قائمة المناصب العليا في المصالح غير المركزية التابعة لوزارة التكوين المهني، وشروط الالتحاق بها وتصنيفها.', 'year': '1997', 'number': '60', 'modified_by': None, 'cancelled_by': None, 'approved_by': None, 'rectified_in': None, 'implemented_by': None}]","[{'level': 2, 'action': 'ملغى بـ', 'title': 'مرسوم تنفيذي رقم 16-225 ممضي في 22 غشت 2016', 'author': None, 'gazette': 'الجريدة الرسمية عدد 51 المؤرخة في 31 غشت 2016، الصفحة 8', 'summary': 'يحدد قائمة المناصب العليا التابعة للمصالح الخارجية لوزارة التكوين والتعليم المهنيين وشروط الالتحاق بهذه المناصب، وكذا الزيادة الاستدلالية المرتبطة بها.', 'year': '2016', 'number': '51', 'modified_by': None, 'cancelled_by': None, 'approved_by': None, 'rectified_in': None, 'implemented_by': None}]",[],[],[]
6,مرسوم تنفيذي رقم 94-470 ممضي في 25 ديسمبر 1994,وزارة الشؤون الدينية,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 13,يتضمن تنظيم الإدارة المركزية في وزارة الشؤون الدينية.,1995,1,[],"[{'level': 2, 'action': 'ملغى بـ', 'title': 'مرسوم تنفيذي رقم 2000-146 ممضي في 28 يونيو 2000', 'author': None, 'gazette': 'الجريدة الرسمية عدد 38 المؤرخة في 02 يوليو 2000، الصفحة 13', 'summary': 'يتضمن تنظيم الإدارة المركزية في وزارة الشؤون الدينية والأوقاف.', 'year': '2000', 'number': '38', 'modified_by': None, 'cancelled_by': None, 'approved_by': None, 'rectified_in': None, 'implemented_by': None}]",[],[],[]
7,قرار ممضي في 15 غشت 1994,وزارة المالية,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 14,يتضمن الموافقة على دفتر الشروط العامة الذي تؤجر وفقه، عن طريق المزاد، العقارات التابعة للأملاك الوطنية الخاصة بالدولة التي تسيرها إدارة الأملاك الوطنية تسييرا مباشرا.,1995,1,[],[],[],[],[]
8,قرار ممضي في 30 نوفمبر 1994,وزارة المالية,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 18,يحدد قائمة البضائع الحساسة القابلة للتهريب.,1995,1,[],[],[],[],[]
9,قرار ممضي في 01 أكتوبر 1994,وزارة الصناعة والطاقة,الجريدة الرسمية عدد 1 مؤرخة في 08 يناير 1995، الصفحة 22,"يتضمن تمديد مدة صلاحية رخصة البحث عن المحروقات في المساحة المسماة ""زمول الأكبر"" (الكتلة : 403أ).",1995,1,[],[],[],[],[]

In [61]:
import json
import pandas as pd

final_json = []

# Loop through the flattened JSON array
for i in range(len(combined_json_flattened)):
    current_obj = combined_json_flattened.iloc[i]

    # If the current object is a pandas Series, convert it to a dictionary
    if isinstance(current_obj, pd.Series):
        current_obj = current_obj.to_dict()

    year = current_obj.get('year')
    number = current_obj.get('number')

    # Check if there is already an entry for this year and number
    existing_entry = next((item for item in final_json if item['year'] == year and item['number'] == number), None)

    if existing_entry:
        # If entry exists, append to the content
        existing_entry['content'].append(current_obj)
    else:
        # If entry doesn't exist, create a new entry
        final_json.append({
            "year": year,
            "number": number,
            "content": [current_obj]
        })

# Write the final_json object to a file
with open('final_json_output.json', 'w', encoding='utf-8') as file:
    json.dump(final_json, file, ensure_ascii=False, indent=4)

print("JSON data successfully written to final_json_output.json")

JSON data successfully written to final_json_output.json

## Exporting

---